# fly.toml app configuration file generated for reactivities-course-inodata on 2024-02-15T04:03:07+08:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'reactivities-course-inodata'
primary_region = 'hkg'

[build]
  image = 'inodata/reactivities:latest'

[env]
  ASPNETCORE_URLS = 'http://+:8080'
  Cloudinary__ApiKey = '593488691528318'
  Cloudinary__CloudName = 'db3yvynam'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
